### PR TITLE
Convert the code to ES6 - Part One.

### PR DESCRIPTION
**Pull request by AlexandreBonneau**
This is the first step for fully converting the codebase to ES6 (var to const & let).
Update the babel configuration to generate source maps as well as managing ES6 code.
Also convert the JSDoc comments (/**) to normal line comments (//) when needed.
Minor corrections here and there.

### CODE REVIEW

**Comment by BobKnothe** [comment]
Let me review.

I do not want to abandon jQuery there should be two versions,

**Comment by Raylehnhoff** [comment]
Would rather see this in TypeScript so people could target whatever ES version their organization needs -- it would cut down on having to maintain ES5 and ES6 versions.

Just my 0.02.

**Comment by jlaustill** [comment]
Typescript would be the worst possible choice.  Es6 and babel will allow you to target es5 even easier than ts.  Just my two cents.

**Comment by Raylehnhoff** [comment]
I'll let the [Angular Team](https://vsavkin.com/writing-angular-2-in-typescript-1fa77c78d8e8#.vvj2ztwll) make that argument for me :)

**Comment by AlexandreBonneau** [comment]
Given the Angular folks (who are surely great people) also pushed Dart quite a lot, and had a weird agenda when pushing Angular 2 over Angular 1, I decided a long time ago that I would mostly ignore all their propaganda ;)

Typescript is indeed interesting for its types, but some say it's not [worth](https://www.quora.com/What-are-the-arguments-against-using-TypeScript?no_redirect=1) [the hassle](http://walkercoderanger.com/blog/2014/02/typescript-isnt-the-answer/).

Moreover it requires all contributors to know Javascript *and* Typescript, which does not lower the barrier to entry to contribute (and we need *moar* contributors!).
It would also add an additional layer of complexity to the project.

Having types would theoretically help us when coding, but we are using always up-to-date JSDoc definitions for each functions with an Eslint rules that enforce those type definitions.
And since we are using modern IDEs (respectively PhpStorm and WebStorm), we already get all the warnings we need when we do something wrong.

Lastly, I already finished the feature-to-feature conversion to ES6 (cf. issue #399) and am currently updating the tests to the new API, so I would not want to convert our newly shiny ES6 code base to that Microsoft-based language ;P

As @jlaustill said, ES5 is not a problem ; I'm pretty happy with the ES6 + babel + webpack process I put in place.

**Comment by Raylehnhoff** [comment]
This is a weak argument.

TypeScript is a superset of javascript. All valid javascript is valid typescript. The argument that "you need to know typescript AND javascript" is borne out of FUD. It's not founded in reality. 

I'd argue that adding the requirement to use babel to transpile is as much of a burden as requiring tsc. I'm a .NET developer and we don't use babel _at all_. You're making the argument that it unduly burdens you, but I could easily make that same argument.

JSDoc and JSLint rules are no substitution for a type system. They enforce your coding style, but that's like saying good documentation and a linter can turn JavaScript into Java -- they aren't comparable. Worse yet, it requires the developers that would theoretically contribute to now need:

JSLint, Babel, and whatever IDE plugins to do these as part of the build step. Porting to TypeScript would require the typescript compiler, which since Angular2 is going to be written entirely in TypeScript, you can reasonably assume most dev shops will have/use.

Furthermore, since all javascript is valid typescript, all ES6 is valid typescript as well. This is where the argument _severely_ breaks down that "typescript is the worst solution" -- it's literally the same thing you're doing now.

While _you_ are happy with the new pipeline, I've worked for several extremely large (Fortune 20-type) companies that use this plugin that do _not_ use this pipeline, and do not support ES6 standards. You could easily just say "Well, they need to modernize", "they need to just transpile it", or "then V3.0 is not for them", but I think that'd be an exceptionally shortsighted thing to do for a jquery-based plugin.

I'd encourage you to actually read about TypeScript, because comments like 

> so I would not want to convert our newly shiny ES6 code base to that Microsoft-based language ;P

are extremely unhealthy if you want to help maintain a project like this, especially when, once again, _all valid javascript is valid typescript_.

**Comment by Raylehnhoff** [comment]
Also to pick at your sources:

1. The "not the answer" page was written 3 years ago, and TS 2.1 has come a _very_ long way. The biggest issues he had are 1) it's still javascript, 2) you need typedefs. Neither are a problem if you _are maintaining an open source library_. There's already even a DefinitelyTyped page for autoNumeric, which is a damn shame that the owners/collaborators of this project do not own it.

2. The quora page also misses the mark that "TypeScript is  a superset of JavaScript". The top post is an argument that someone that's never used TS would make. I don't buy the argument of added complexity when it comes to the other quora posts. I challenge you to find an _actual_ engineering firm that has come out against typescript in the last 2 years.

In the end, this is a holywar and I doubt @BobKnothe cares very much about it. I want to see this project stay relevant, portable, and adopted. I have deep concerns about abstracting away from ES5 at this stage, since I suspect if @BobKnothe did a poll of the major entities that use this plugin, many of them are still supporting non-ES6 compliant browsers.

**Comment by AlexandreBonneau** [comment]
You assume Angular 2 is what *most dev shops will have/use*, I beg to differ.
Google did a great job at alienating its own users during the Angular 1 to Angular 2 transition.
That's partly why Vue.js (ES6) is [taking the lead](http://bestof.js.org/tags/framework/popular) at a great speed, and Angular is [slowly declining](https://www.google.com/trends/explore?q=Vue.js,React.js,Angular.js).

You also assume I'm against Typescript, which I'm not. I do think typed languages are better.
I just do not want to take the time to convert the code base to it (specially since I prefer pure Javascript), and prefer to focus my time on creating new awesome features.

But all this is a moot point since it's really just a matter of language preferences (and who can argue with a personal choice?), since thanks to Babel, even if *major entities [...] are still suppporting non-ES6 compliant browsers*, who cares, autoNumeric `dist` files are in ES5 ! :)

No user of autoNumeric needs any *pipeline* to use it (since it's already transpiled to ES5 thanks to Babel), only contributors need to know how to use `yarn && yarn build` in order to make their contributions transpiled into ES5 as well.

I'm not sure to follow what you are trying to say here, sorry.
If you fear converting the *source* to an ES6 module will make it harder for users using obsolete browsers to use it, don't; again, the generated `dist` files are in ES5!

On the other hand, if you feel a typescript version of autoNumeric is needed, then feel free to contribute! :)

**Comment by jlaustill** [comment]
This conversation took an interesting turn :)  I am actually a Microsoft certified C# developer, and have spent my fair share of time on the asp.net stack.  But I'm also a nodejs developer, and most recently a php developer.  

I got burned by angular 1 to 2 BIG time, I'm now a very happy knockoutjs user.  I can't imagine ever giving a huge framework another chance again after having to go through that, grr.  But I digress.

I think the biggest thing missing from this conversation is the fact that at some point ES6 will be supported by browsers and we'll be able to run it natively.  That's a huge, huge, huge advantage in my book.  I already have so many languages to keep up on, and so many libraries, I do not need more languages just for the sake of more languages.

**Pull request merged**
