### PR TITLE
Fix main file name in package.json

### PR DESCRIPTION
**Pull request by kossnocorp**
… since `autonumeric.js` was renamed (right?) to `autoNumeric.js`.

### CODE REVIEW

**Comment by BobKnothe** [comment]
Thanks - I will check. 



 
Robert (Bob) Knothe

**Comment by kossnocorp** [comment]
@BobKnothe could you release the fixed package?

**Comment by BobKnothe** [comment]
Sasha,
 
I found the error and will be posting the fix when I get back to my office Friday.
 
Bob
 
--------- Original Message --------- Subject: Re: [autoNumeric] Fix main file name in package.json (#177)

**Comment by BobKnothe** [comment]
If you want to fix locally in the autoRound function replace the following
 
this                    ivRounded += '.';
with                   ivRounded += settings.aDec;
 
 
 
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] Fix main file name in package.json (#177)

**Pull request merged**
