### PR TITLE
Rails gem link

### PR DESCRIPTION
**Pull request by randoum**
If you don't mind, I'd like to add the link to my gem repository into your readme, that is to easy ruby-on-rails developpers to find the gem.

Cheers

### CODE REVIEW

**Comment by BobKnothe** [comment]
sure no problem

Have you looked at my latest 2.0 beta (https://github.com/BobKnothe/autoNumeric/tree/master/autoNumeric-2.0)?

I am getting close to release - first adding a un-format on submit and some type of hooks for jQuery validate.

**Comment by randoum** [comment]
Thanks.

I haven't look at it yet.
Actually the main purpose of the gem, aside of easy integration of the library, is indeed to "un-format on submit" so the values are correctly sent to the back end as a numeric format. That's why I'm waiting for your v2 to finalised.

Let me know if I can help

**Comment by BobKnothe** [comment]
I just uploaded the latest version with two new options

+ Added option "unSetOnSubmit" to unformat input on the submit event
+ Added option "debug" to turn on and off error being thrown

I would be very helpful if you could test the unSetOnSubmit option

**Comment by randoum** [comment]
Sure, give me a day or two. 

btw, you should have a look at jasmine and/or selenium (or capybara or cucumber) if not yet. awesomely useful for unit and integration testing

**Comment by randoum** [comment]
Sorry Bob, I was super busy. Did not forget about it, just didn't have time

**Comment by randoum** [comment]
I had some issues, but I finally was able to integrate v2 into my gem

**Pull request merged**
