### PR TITLE
Set bower.json license to MIT like package.json

### PR DESCRIPTION
**Pull request by nicolashenry**
I use http://www.webjars.org/bower but webjars seems to not support this url as license for deployment.

### CODE REVIEW

**Comment by nicolashenry** [comment]
@BobKnothe Does it seem correct to you ?

**Comment by BobKnothe** [comment]
So all you want is to change the link to MIY?
 
 
--------- O GBriginal Message --------- Subject: Re: [BobKnothe/autoNumeric] Set bower.json license to MIT like package.json (#202)

**Comment by nicolashenry** [comment]
Yes, because the link is not recognized as a valid license for WebJars, I am stuck with version 1.9.30 if you don't accept (see https://github.com/webjars/webjars/issues/1074).

**Comment by BobKnothe** [comment]
Is there a link that works?



 
Robert (Bob) Knothe

**Comment by nicolashenry** [comment]
Maybe "https://spdx.org/licenses/MIT.html" if you really want an URL (see https://github.com/bower/spec/blob/master/json.md#license) but I am not sure it can work. I think that just the string "MIT" is safer. 

Another solution would be to rename "license.txt" to "LICENSE.txt" (like jQuery repository) or "LICENSE" because WebJar seems to search these file names as an alternative.

**Comment by nicolashenry** [comment]
@BobKnothe Should I do something else ?

**Comment by BobKnothe** [comment]
its just time management or lackNext week is when I will have time - thanks for your patience.


-------- Original Message --------
Subject: Re: [BobKnothe/autoNumeric] Set bower.json license to MIT like
package.json (#202)

**Comment by AlexandreBonneau** [comment]
`bower` support has been deprecated in favor of `npm`, and hence, the `bower.json` file does not exists anymore.

**Pull request closed without merging**
