### PR TITLE
Rails gem link

### PR DESCRIPTION
**Pull request by randoum**
Finally released rails gem for AN v2
Ref: #162

### CODE REVIEW

**Comment by AlexandreBonneau** [comment]
Hi, v2.0 is not out yet though (we are at beta ~18 approx.).

**Comment by randoum** [comment]
Yes. I was mentioning my gem. It's v2 ready

**Comment by AlexandreBonneau** [comment]
Thank you @randoum for your interest in autoNumeric and helping us making it even better!

Would it be possible to create this pull request against the latest `next` [branch](https://github.com/BobKnothe/autoNumeric/tree/next)?

Also, I could see that line
```
For integration into rails projects, see the [autonumeric-rails](https://github.com/randoum/autonumeric-rails) project.
```
find its place into the newly created `'Related projects'` chapter in that `README.md` file.

Is it ok with you?

**Comment by AlexandreBonneau** [comment]
This PR is obsolete and has been replaced by #337.

**Pull request closed without merging**
